// Industry options
export const INDUSTRIES = [
  'AI',
  'AI/AR/VR (Augmented + Virtual Reality)',
  'Aeronautics, Aerospace & Defence',
  'Agriculture',
  'Airport Operations',
  'Analytics',
  'Animation',
  'Architecture & Interior Design',
  'Art & Photography',
  'Automotive',
  'Advertising',
  'Biotechnology',
  'Chemicals',
  'Computer Vision',
  'Construction',
  'Dating & Matrimonial',
  'Design',
  'Education',
  'Enterprise Software',
  'Events',
  'Fashion',
  'Finance Technology (FinTech)',
  'Food & Beverages',
  'Green Technology',
  'Healthcare & Lifesciences',
  'Household Services',
  'Human Resources',
  'Indic Language Startups',
  'Internet of Things (IoT)',
  'IT Services',
  'Logistics',
  'Marketing',
  'Media & Entertainment',
  'Nanotechnology',
  'Non-Renewable Energy',
  'Other Specialty Retailers',
  'Others',
  'Passenger Experience',
  'Pets & Animals',
  'Professional & Commercial Services',
  'Real Estate',
  'Renewable Energy',
  'Retail',
  'Robotics',
  'Robotics Technology',
  'Safety',
  'Security Solutions',
  'Social Impact',
  'Social Network',
  'Sports',
  'Technology Hardware',
  'Telecommunication & Networking',
  'Textiles & Apparel',
  'Toys & Games',
  'Transportation & Storage',
  'Travel & Tourism',
  'Waste Management'
] as const

// Sector options
export const SECTORS = [
  '3D Printing',
  'Accounting',
  'AdTech',
  'Advisory',
  'Agricultural Chemicals',
  'Agri-Tech',
  'Agnostic Sector',
  'Animal Husbandry',
  'Apparel',
  'Apparel & Accessories',
  'Application Development',
  'Art',
  'Assistive Technology',
  'Assistance Technology',
  'Auto & Truck Manufacturers',
  'Auto, Truck & Motorcycle Parts',
  'Auto Vehicles, Parts & Service Retailers',
  'Aviation & Others',
  'Baby Care',
  'Big Data',
  'Billing and Invoicing',
  'Biotechnology',
  'Bitcoin and Blockchain',
  'Blockchain',
  'BPO',
  'Branding',
  'Business Finance',
  'Business Intelligence',
  'Business Support Services',
  'Business Support Supplies',
  'Child Protection',
  'Circular Economy',
  'Clean Tech',
  'Cloud',
  'Coaching',
  'Collaboration',
  'Commercial Printing Services',
  'Commodity Chemicals',
  'Comparison Shopping',
  'Computer & Electronics Retailers',
  'Construction & Engineering',
  'Construction Materials',
  'Construction Supplies & Fixtures',
  'Corporate Social Responsibility',
  'Coworking Spaces',
  'CXM',
  'Cyber Security',
  'Customer Support',
  'Data Analysis',
  'Data Science',
  'Dairy Farming',
  'Deep Tech',
  'Defence Equipment',
  'Digital Health',
  'Digital Marketing (SEO Automation)',
  'Digital Media',
  'Digital Media Blogging',
  'Digital Media News',
  'Digital Media Publishing',
  'Digital Media Video',
  'Discovery',
  'Diversified Chemicals',
  'Drones',
  'E-Commerce',
  'E-learning',
  'Edge Computing',
  'Education',
  'Education Technology',
  'Electric Vehicles',
  'Electronics',
  'Embedded',
  'Employment Services',
  'Entertainment',
  'Environmental Services & Equipment',
  'ERP',
  'Event Management',
  'Experiential Travel',
  'Facility Management',
  'Fantasy Sports',
  'Fan Merchandise',
  'Fashion Technology',
  'Fisheries',
  'FMCG',
  'Food Processing',
  'Food Technology/Food Delivery',
  'Foreign Exchange',
  'Freight & Logistics Services',
  'Handicraft',
  'Health & Wellness',
  'Healthcare IT',
  'Healthcare Services',
  'Healthcare Technology',
  'Holiday Rentals',
  'Home Care',
  'Home Furnishings Retailers',
  'Home Improvement Products & Services Retailers',
  'Home Security Solutions',
  'Homebuilding',
  'Horticulture',
  'Hospitality',
  'Hotel',
  'Housing',
  'Industrial Design',
  'Infrastructure',
  'Integrated Communication Services',
  'Internships',
  'Insurance',
  'IoT',
  'IoT Machine Learning',
  'IT Consulting',
  'IT Management',
  'Jewellery',
  'KPO',
  'Legal-Tech',
  'Leather Footwear',
  'Leather Textiles Goods',
  'Lifestyle',
  'Location-Based',
  'Logistics',
  'Loyalty',
  'Machine Learning',
  'Manufacture of Electrical Equipment',
  'Manufacture of Machinery and Equipment',
  'Manufacturing',
  'Manufacturing & Warehouse',
  'Manufacturing and Allied Engineering Sectors',
  'Marine Tourism',
  'Market Research',
  'Medical Devices & Biomedical',
  'Media and Entertainment',
  'Microbrewery',
  'Microfinance',
  'Mobile Wallets & Payments',
  'Movies',
  'Natural Language Processing (NLP)',
  'New-age Construction Technologies',
  'NGO',
  'Non-Leather Footwear',
  'Non-Leather Textiles Goods',
  'Oil & Gas Drilling',
  'Oil & Gas Exploration and Production',
  'Oil & Gas Transportation Services',
  'Oil Related Services and Equipment',
  'Online Classified',
  'OOH Media',
  'Organic Agriculture',
  'Others',
  'Passenger Transportation Services',
  'Payment Platforms',
  'Personal Care',
  'Personal Finance',
  'Personal Security',
  'Pharmaceutical',
  'Physical Toys and Games',
  'Photography',
  'Point of Sales',
  'Product Development',
  'Professional Information Services',
  'Project Management',
  'Public Citizen Security Solutions',
  'Recruitment & Jobs',
  'Renewable Energy Solutions',
  'Renewable Nuclear Energy',
  'Renewable Solar Energy',
  'Renewable Wind Energy',
  'Retail Technology',
  'Robotics Application',
  'Robotics Technology',
  'Sales',
  'SCM (Supply Chain Management)',
  'Semiconductor',
  'Ships and Ports Infrastructure',
  'Skills Assessment',
  'Skill Development',
  'Smart City',
  'Smart Home',
  'Smart Home Space Technology Wearables',
  'Social Commerce',
  'Social Media',
  'Space Technology',
  'Sports Promotion and Networking',
  'Sustainable Blue Economy',
  'Talent Management',
  'Technology',
  'Testing',
  'Ticketing',
  'Tires & Rubber Products',
  'Trading',
  'Traffic Management',
  'Training',
  'Transport Infrastructure',
  'Unmanned Aerial Vehicles',
  'Utility Services',
  'Virtual Games',
  'Water and Sanitation',
  'Wayside Amenities',
  'Web Design',
  'Web Development',
  'Weddings',
  'Wireless'
] as const

// Stage completed options
export const STAGES_COMPLETED = [
  'Proof of Concept',
  'Prototype development',
  'Product Development',
  'Field Trials',
  'Market Launch'
] as const 